--
-- PostgreSQL database dump
--

-- Dumped from database version 13.6
-- Dumped by pg_dump version 13.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: CarrinhoCompraItens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CarrinhoCompraItens" (
    "CarrinhoCompraItemId" integer NOT NULL,
    "LancheId" integer,
    "Quantidade" integer NOT NULL,
    "CarrinhoCompraId" character varying(200)
);


ALTER TABLE public."CarrinhoCompraItens" OWNER TO postgres;

--
-- Name: CarrinhoCompraItens_CarrinhoCompraItemId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CarrinhoCompraItens" ALTER COLUMN "CarrinhoCompraItemId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CarrinhoCompraItens_CarrinhoCompraItemId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Categorias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Categorias" (
    "CategoriaId" integer NOT NULL,
    "CategoriaNome" character varying(100) NOT NULL,
    "Descricao" character varying(200) NOT NULL
);


ALTER TABLE public."Categorias" OWNER TO postgres;

--
-- Name: Categorias_CategoriaId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Categorias" ALTER COLUMN "CategoriaId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categorias_CategoriaId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Lanches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Lanches" (
    "LancheId" integer NOT NULL,
    "Nome" character varying(80) NOT NULL,
    "DescricaoCurta" character varying(200) NOT NULL,
    "DescricaoDetalhada" character varying(200) NOT NULL,
    "Preco" numeric(10,2) NOT NULL,
    "ImagemUrl" character varying(200),
    "ImagemThumbnailUrl" character varying(200),
    "IsLanchePreferido" boolean NOT NULL,
    "EmEstoque" boolean NOT NULL,
    "CategoriaId" integer NOT NULL
);


ALTER TABLE public."Lanches" OWNER TO postgres;

--
-- Name: Lanches_LancheId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Lanches" ALTER COLUMN "LancheId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Lanches_LancheId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: CarrinhoCompraItens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CarrinhoCompraItens" ("CarrinhoCompraItemId", "LancheId", "Quantidade", "CarrinhoCompraId") FROM stdin;
\.


--
-- Data for Name: Categorias; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Categorias" ("CategoriaId", "CategoriaNome", "Descricao") FROM stdin;
4	Naturais	Produtos realizados com ingredientes naturais
5	Industrializados	Produtos realizados com ingredientes industriais
\.


--
-- Data for Name: Lanches; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Lanches" ("LancheId", "Nome", "DescricaoCurta", "DescricaoDetalhada", "Preco", "ImagemUrl", "ImagemThumbnailUrl", "IsLanchePreferido", "EmEstoque", "CategoriaId") FROM stdin;
6	Pão com presunto	Pão caseiro presunto	Pão de brioche, com presunto seara e amateigado	12.00	https://t3.ftcdn.net/jpg/01/82/43/26/360_F_182432679_9IUAzFEU7jzTFJcnZChiVP4mnGhU21v2.jpg	https://t3.ftcdn.net/jpg/01/82/43/26/360_F_182432679_9IUAzFEU7jzTFJcnZChiVP4mnGhU21v2.jpg	f	t	5
7	Pão com ovo	Pão caseiro com ovo frito	Pão de brioche, com ovo classe A e amateigado	12.00	https://t3.ftcdn.net/jpg/01/82/43/26/360_F_182432679_9IUAzFEU7jzTFJcnZChiVP4mnGhU21v2.jpg	https://t3.ftcdn.net/jpg/01/82/43/26/360_F_182432679_9IUAzFEU7jzTFJcnZChiVP4mnGhU21v2.jpg	t	t	4
8	Pão com presunto e ovo	Pão caseiro com ovo e presunto	Pão de brioche, com presunto seara e amateigado e ovo classe A	14.00	https://t3.ftcdn.net/jpg/01/82/43/26/360_F_182432679_9IUAzFEU7jzTFJcnZChiVP4mnGhU21v2.jpg	https://t3.ftcdn.net/jpg/01/82/43/26/360_F_182432679_9IUAzFEU7jzTFJcnZChiVP4mnGhU21v2.jpg	f	f	5
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20230308175244_MigracaoInicial	6.0.0
20230309203435_PopularCategoria	6.0.0
20230310120145_PopularLanche	6.0.0
20230311234933_CarrinhoCompraItem	6.0.0
\.


--
-- Name: CarrinhoCompraItens_CarrinhoCompraItemId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CarrinhoCompraItens_CarrinhoCompraItemId_seq"', 1, false);


--
-- Name: Categorias_CategoriaId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Categorias_CategoriaId_seq"', 5, true);


--
-- Name: Lanches_LancheId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Lanches_LancheId_seq"', 8, true);


--
-- Name: CarrinhoCompraItens PK_CarrinhoCompraItens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CarrinhoCompraItens"
    ADD CONSTRAINT "PK_CarrinhoCompraItens" PRIMARY KEY ("CarrinhoCompraItemId");


--
-- Name: Categorias PK_Categorias; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Categorias"
    ADD CONSTRAINT "PK_Categorias" PRIMARY KEY ("CategoriaId");


--
-- Name: Lanches PK_Lanches; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Lanches"
    ADD CONSTRAINT "PK_Lanches" PRIMARY KEY ("LancheId");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_CarrinhoCompraItens_LancheId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_CarrinhoCompraItens_LancheId" ON public."CarrinhoCompraItens" USING btree ("LancheId");


--
-- Name: IX_Lanches_CategoriaId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Lanches_CategoriaId" ON public."Lanches" USING btree ("CategoriaId");


--
-- Name: CarrinhoCompraItens FK_CarrinhoCompraItens_Lanches_LancheId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CarrinhoCompraItens"
    ADD CONSTRAINT "FK_CarrinhoCompraItens_Lanches_LancheId" FOREIGN KEY ("LancheId") REFERENCES public."Lanches"("LancheId");


--
-- Name: Lanches FK_Lanches_Categorias_CategoriaId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Lanches"
    ADD CONSTRAINT "FK_Lanches_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES public."Categorias"("CategoriaId") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

